// vuejs/src.old/components/Form.vue
<template>
	<div class='form'>
		<div class='form_row'>
			<label>Name</label>
			<input name='name' v-bind:value="edit.name" />
		</div>
	</div>
</template>

<script>
export default
{
	props: ["active_id", "list"],
	computed: {
		/*
		edit: function() {
			var item = null;
			for (var i=0; i<this.list.length++; i++)
			{
				if (this.list[i].id == this.active_id)
				{
					item = this.list[i];
					break;
				}
			}
			return null;
		},
		*/
	}
}
</script>

<style>
</style>

// sveltejs/src/components/Form.svelte
<style>
.form_row{
}
.form_row label{
	font-weight: bold;
	display: block;
	text-align: left;
	padding-bottom: 5px;
}
.form_row input{
	width: 100%;
	padding: 6px 12px;
}
</style>



{#if item != null}

<div class='form'>
	<div class='form_row'>
		<label>Name</label>
		<input
			name='name' placeholder="enter your name" bind:value={ item.name }
		/>
	</div>
</div>

{/if}


<script>
	export let item = null;
</script>
